nks:
  frontend-base-url: ${FRONTEND_BASE_URL}   # obligatoire — à déclarer dans les variables Jelastic

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: false

server:
  forward-headers-strategy: framework

logging:
  level:
    bf.laterrasse.nks: DEBUG
    root: WARN
